describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://172.30.32.1:5173/JS3-exam/')
    cy.get('.startBtn').click()
    cy.get('.recipeBtn').click()
    cy.get('#cardFrukost').click()
    cy.get('#id-85d21bd5-26e6-4635-87e0-002bcaf02de6').click()
    cy.get('.editBtn').click()
    cy.get('.changeTitle').type('!')
    cy.get('.changeDesc').type('!')
    cy.get('input[type=file]').selectFile('cypress\\fixtures\\ff52b5a0-f879-460b-9893-b668feec50e6.webp')
    cy.get('#changeTTC').type('0')
    cy.get('#changePortions').type('!')
    cy.get('#ingredient-0').type('!')
    cy.get('#newIngredient').type('!')
    cy.get('#newIngredientBtn').click()
    cy.get('#instruction-0').type('!')
    cy.get('#newInstruction').type('!')
    cy.get('#newInstructionBtn').click()
    cy.get('.saveBtn').click()
  })
})